[package]
name = "enzyme_playground"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
ndarray = { version = "0.16.1", features = ["approx"] }
num-dual = { version = "0.9.1", features = ["ndarray"] }

[profile.release]
lto = "fat"

[dev-dependencies]
approx = "0.5.1"
